Update README.md
Ericgacoki/Sudofy pull request #5
Opened 2021-03-29 20:16 UTC by Kimosop-Wakanda

2021-03-29 20:38 UTC, Ericgacoki commented on README.md
> +A project the for Google Solution Challenge - 2021 (`Health monitoring system`)
Hey @Kimosop-Wakanda, the grammar in this sentence doesn't flow so well, please correct that.

2021-03-30 03:18 UTC, Ericgacoki requested changes
Please make the changes ASAP.

2021-03-30 09:33 UTC, Ericgacoki approved these changes
checked

2021-03-30 09:36 UTC, merged

2021-03-30 09:38 UTC, Ericgacoki commented
Nice work @Kimosop-Wakanda, next time please `ping` the reviewer when you're done with the changes.

2021-03-30 10:35 UTC, Kimosop-Wakanda commented
Okay and
Good Luck with the project

On Tue, 30 Mar 2021, 12:38 Eric G, ***@***.***> wrote:

> Nice work @Kimosop-Wakanda <https://github.com/Kimosop-Wakanda>, next
> time please ping the reviewer when you're done with the changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ericgacoki/sudofy/pull/5#issuecomment-810074404>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APDOHGQCKIY3MFXHE36OEDTTGGLYVANCNFSM42AKDRQQ>
> .
>